#!/bin/sh

### BEGIN INIT INFO
# Provides: Blog
# Required-Start: $network $remote_fs $local_fs
# Required-Stop: $network $remote_fs $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Blog
# Description: Blog Service Program
### END INIT INFO

start(){
  echo  'starting Blog Service: '
  sh /blog/setup.sh
  return 0
}

stop(){
  echo  'Shutting down Blog Service: '
  PID=$(ps -ef | grep "my-blog-3.0.1-SNAPSHOT.war" | grep -v grep | awk '{print $2}')
  if [ ! -z "${PID}" ];
  then
          kill -9 ${PID}
  fi
  return 0
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
esac

exit 0
